name: Renovate

on: workflow_dispatch

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Access Token
        run: .github/scripts/get_azure_access_token.sh
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Check token length
        run: echo "${AZURE_ACCESS_TOKEN}" | wc -c
      
      - name: Renovate
        uses: renovatebot/github-action@v40.2.8
        with:
          configurationFile: config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
          env-regex: "^(?:RENOVATE_\\w+|LOG_LEVEL|GITHUB_COM_TOKEN|NODE_OPTIONS|AWS_TOKEN|AZURE_ACCESS_TOKEN)$"
        env:
          LOG_LEVEL: 'debug'
